# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy file sto : $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/bin/$(BuildConfiguration)/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs: 
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    
- task: DownloadSecureFile@1
  displayName: 'Download seettings.xml secure file'
  inputs: 
    secureFile: 'settings.xml'
- task: Bash@3
  displayName: 'Copy settings.xml secure file into !/.m2'
  inputs: 
    targetType: 'inline'
    script: mkdir ~/.m2/
    cp "$(Agent.TempDirectory)/settings.xml" ~/.m2/  